/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
namespace zFramework.TinyRPC.Generated
{
    public struct PlayerInfo
    {
        public string name;
        public int playerid;
        /// <summary>
        ///  当首次获取时，此值等效为初始化点位
        /// </summary>
        public MoveInfo moveinfo;
    }
}
