/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  移动信息
    /// </summary>
    [Serializable]
    public partial class MoveInfo : Message
    {
        /// <summary>
        ///  初始化坐标 x 轴向
        /// </summary>
        public float X;
        /// <summary>
        ///  初始化坐标 y 轴向
        /// </summary>
        public float Y;
        /// <summary>
        ///  初始化坐标 z 轴向
        /// </summary>
        public float Z;
        public float A;
        public float B;
        public float C;
        public float W;
        public int speed;
        public override void OnRecycle()
        {
            base.OnRecycle();
            X = 0f;
            Y = 0f;
            Z = 0f;
            A = 0f;
            B = 0f;
            C = 0f;
            W = 0f;
            speed = 0;
        }
    }
}
