/*
*代码由 TinyRPC 自动生成，请勿修改
*don't modify manually as it generated by TinyRPC
*/
using System;
using zFramework.TinyRPC.Messages;
namespace zFramework.TinyRPC.Generated
{
    /// <summary>
    ///  服务器定期请求玩家上报姿态信息
    /// </summary>
    [Serializable]
    public partial class S2C_RequirePlayerPose : Message
    {
        /// <summary>
        ///  请求发生在哪一帧
        /// </summary>
        public int frame;
        public override void OnRecycle()
        {
            base.OnRecycle();
            frame = 0;
        }
    }
}
